### ISSUE TITLE
Cannot Start Project

### ISSUE THREAD

**Issue by Pigweed** [aws-samples/amazon-chime-sdk-smart-video-sending-demo#6]
Hi there. Trying to get your project loaded and running and am running into three errors that I hope you can help with... Running on Windows 10 by the way. And, the packages seem to install and run properly.

First, the URL https://0.0.0.0:9000  does not load. 
Second, the URL http://localhost:8080/ returns a json error: {"error":"ENOENT: no such file or directory, open 'dist/meeting.html'"}
Third, the URL https://127.0.0.1:9000/ logs a javascript error to the console: WebSocket connection to 'wss://127.0.0.1:9000/sockjs-node/192/4cc4cpi5/websocket' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

Can you give any recommendations on how to get your application up and running. Any help is greatly appreciated. 

Thanks.

**Comment by p-foucht** [comment]
Hi @Pigweed 

Can you run `npm run build` after the `install` step? After this, you should be able to run the app and open it with `https://0.0.0.0:9000/` as normal. I've pushed a change to the README to include this step so others don't run into the same issue.

Resolving, but if the above doesn't fix please reopen and let me know and I will continue to troubleshoot!
